language: node_js
node_js: '12'
cache:
  yarn: true

addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN

before_install:
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - yarn config set @xmess:registry "https://registry.npmjs.org"
  - yarn config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN

install:
  - yarn

script:
  - yarn ci:lint
  - yarn ci:build
  - yarn ci:test
  - yarn ci:sonar -D sonar.host.url=$SONAR_HOST_URL -X

before_deploy:
  - git checkout ${TRAVIS_BRANCH}
  - yarn config set @xmess:registry "https://registry.npmjs.org"
  - yarn config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN

deploy:
  provider: script
  script: yarn ci:publish
  skip_cleanup: true
  on:
    branch: master
