language: node_js
node_js: "10"
cache:
  yarn: true

addons:
 sonarcloud:
   organization: ciklum-digital
   token:
     secure: $SONAR_TOKEN

before_install:
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

install:
  - yarn

script:
  - npm run lint
  - npm run test:ci
  - npm run sonar
  - npm run build

before_deploy:
  - git checkout ${TRAVIS_BRANCH}

deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
    branch: master
