language: node_js
node_js: "10"

before_install:
  - git remote add origin "https://${GITHUB_TOKEN}@github.com/ciklum-digital/xmess.git"
  - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

install:
  - npm ci --quite
  - npm run bootstrap

script:
  - npm run build
  - npm run lint
  - npm test

before_deploy:
  - git checkout master

deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
#    tags: true
    branch: master
